@REM Generated By GPT
@REM Modified By CD
@echo off
setlocal enabledelayedexpansion

if "%1"=="" (
    echo Usage: %0 ^<command^>
    echo.
    echo Available commands: install, run, build
    exit /b 1
)

set CMD=%1

if /i "%CMD%"=="install" goto install
if /i "%CMD%"=="run" goto run
if /i "%CMD%"=="build" goto build

echo Invalid command: %CMD%
exit /b 1

:install
cd .theme && npm i && cd ..
goto end

:run
echo (1) dev
echo (2) local
set /p choice="Please select 1-2: "

if "%choice%"=="1" goto dev
if "%choice%"=="2" goto local

:dev
cd .theme && npm run dev && cd ..
goto end

:local
cd .theme && npm run local && cd ..
goto end

:build
cd .theme && npm run generate:local && cd ..
goto end

:end
